name: Rust Linting

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  Clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Move rust files up one directory
        run: mv native ..
        shell: bash
      - name: Install rustup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      # - name: Run Clippy
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy
      #     args: -- --check
      - name: Run Clippy
        run: |
          #!/bin/bash
          cd native
          cargo clippy -- --check
  Rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install rustup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Rustfmt
        run: rustup component add rustfmt
      - name: Run Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
